# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwCIcS89e_T9JiALYYI-BIPZPVh5bUrC
"""

import numpy as np
import matplotlib.pyplot as plt
import gc  # Added for memory management

class ArtificialCell:
    def __init__(self, position, weights=None, lineage_id=0):
        self.position = np.array(position, dtype=float)
        self.energy = 100.0  # Stage 1: Metabolic Energy Budget
        self.age = 0
        self.is_alive = True
        self.lineage_id = lineage_id

        # Stage 2: Lineage Memory (Neural weights controlling behavior)
        if weights is None:
            # 3 Inputs: [X_dist_to_vent, Y_dist_to_vent, Internal_Energy]
            # 2 Outputs: [X_velocity, Y_velocity]
            self.weights = np.random.uniform(-1.0, 1.0, (3, 2))
        else:
            # Replication with error (Mutation)
            mutation_rate = 0.05
            self.weights = weights + np.random.normal(0, mutation_rate, size=weights.shape)

    def act(self, vent_position):
        # Stage 4: Active Inference / Minimizing Surprise
        # Calculate sensory inputs
        delta = vent_position - self.position
        sensory_inputs = np.array([delta[0], delta[1], self.energy])

        # Compute movement vector via matrix multiplication
        outputs = np.dot(sensory_inputs, self.weights)
        movement = np.tanh(outputs)  # Bounds movement between -1 and 1

        # Apply movement and metabolic cost
        self.position += movement
        self.energy -= 0.5  # Tuned thermodynamic cost
        self.age += 1

        if self.energy <= 0:
            self.is_alive = False

def run_simulation(generations=100, steps_per_gen=200):
    vent_position = np.array([25.0, 25.0])  # Energy center
    # Initial population set to 100 for better genetic diversity
    population = [ArtificialCell(np.random.uniform(0, 50, 2), lineage_id=i) for i in range(100)]

    history_lifespan = []

    for gen in range(generations):
        for step in range(steps_per_gen):
            next_population = []
            for cell in population:
                if not cell.is_alive:
                    continue

                # Check if cell gathered energy from the vent
                distance_to_vent = np.linalg.norm(cell.position - vent_position)

                # Vent radius
                if distance_to_vent < 15.0:
                    cell.energy += 15.0  # Energy reward

                cell.act(vent_position)

                if cell.is_alive:
                    # Stage 1 & 2: Replication Threshold
                    if cell.energy >= 200.0:
                        cell.energy /= 2.0  # Split energy
                        # Spawn mutated child
                        child = ArtificialCell(cell.position.copy(), cell.weights.copy(), cell.lineage_id)
                        next_population.append(child)
                    next_population.append(cell)

            # --- CARRYING CAPACITY BOTTLENECK ---
            # If the population explodes, only the fittest survive
            if len(next_population) > 500:
                next_population.sort(key=lambda c: c.energy, reverse=True)
                next_population = next_population[:500]
            # ------------------------------------

            population = next_population
            if len(population) == 0:
                print(f"\nExtinction occurred at generation {gen}.")
                break

        # Track metrics
        if population:
            avg_age = np.mean([c.age for c in population])
            history_lifespan.append(avg_age)

            # Console reporting for real-time tracking
            print(f"Generation {gen} complete | Population: {len(population)} | Avg Lifespan: {avg_age:.1f}")

            # Reset cell positions and age for next epoch, retaining weights ("the soul")
            for c in population:
                c.position = np.random.uniform(0, 50, 2)
                c.energy = 100.0
                c.age = 0

            # Sweep the RAM clean of dead cells to prevent crashes
            gc.collect()
        else:
            break

    # Plot evolutionary adaptation
    if history_lifespan:
        plt.plot(history_lifespan)
        plt.title("Evolution of Lifespan Under Homeostatic Pressure")
        plt.xlabel("Generation")
        plt.ylabel("Average Lifespan (Steps)")
        plt.grid(True)
        plt.savefig("evolution_plot.png")
        plt.show()
        print(f"\nSimulation finished. Final population size: {len(population)}")

if __name__ == "__main__":
    run_simulation()